Evaluacion/Models/Articulo.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Evaluacion.Models
{
    public class Articulo
    {
        public int Art_ID { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
    }
}

Evaluacion/Controllers/ArticulosController.cs
using Evaluacion.Models;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Evaluacion.Controllers
{
    public class ArticulosController : Controller
    {
        public ActionResult Index()
        {
            var client = new RestClient("https://localhost:44382/api/Articulos");
            var request = new RestRequest(new Uri("https://localhost:44382/api/Articulos"), Method.Get);
            var response = client.Execute(request);
            List<Articulo> items = JsonConvert.DeserializeObject<List<Articulo>>(response.Content);

            return View(items);
        }

        // GET: Articulos/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Articulos/Create
        public ActionResult Create()
        {
            Articulo art = new Articulo();
            return PartialView("_ArticuloData", art);
        }

        // POST: Articulos/Create
        [HttpPost]
        public ActionResult Create(Articulo art)
        {
            try
            {
                var client = new RestClient("https://localhost:44382/api/Articulos");
                var request = new RestRequest(new Uri("https://localhost:44382/api/Articulos"), Method.Post);
                request.AddHeader("Content-Type", "application/json");
                var body = JsonConvert.SerializeObject(art);
                request.AddParameter("application/json", body, ParameterType.RequestBody);
                var response = client.Execute(request);
                //Console.WriteLine(response.Content);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Articulos/Edit/5
        public ActionResult Edit(int id)
        {
            var client = new RestClient("https://localhost:44382/api/Articulos/" + id);
            var request = new RestRequest(new Uri("https://localhost:44382/api/Articulos/" + id), Method.Get);
            var response = client.Execute(request);
            Articulo item = JsonConvert.DeserializeObject<Articulo>(response.Content);

            return PartialView("_ArticuloDataEdit", item);
        }

        // POST: Articulos/Edit/5
        [HttpPost]
        public ActionResult Edit(Articulo art)
        {
            try
            {
                var client = new RestClient("https://localhost:44382/api/Articulos/" + art.Art_ID.ToString());
                var request = new RestRequest(new Uri("https://localhost:44382/api/Articulos/" + art.Art_ID.ToString()), Method.Put);
                request.AddHeader("Content-Type", "application/json");
                var body = JsonConvert.SerializeObject(art);
                request.AddParameter("application/json", body, ParameterType.RequestBody);
                var response = client.Execute(request);
                //Console.WriteLine(response.Content);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Articulos/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        // POST: Articulos/Delete/5
        [HttpPost]
        public ActionResult Delete(int id)
        {
            try
            {
                if (id > 0)
                {
                    var client = new RestClient("https://localhost:44382/api/Articulos/" + id.ToString());
                    var request = new RestRequest(new Uri("https://localhost:44382/api/Articulos/" + id.ToString()), Method.Delete);
                    var response = client.Execute(request);
                }

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Evaluacion/Views/Articulos/Index.cshtml
@model IEnumerable<Evaluacion.Models.Articulo>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="PlaceHolderHere"></div>

<h2>Articulos</h2>

<button type="button" class="btn btn-primary" data-toggle="ajax-modal" data-target="#addArticulo"
        data-url="@Url.Action("Create")">
    Nuevo
</button>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Art_ID)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Codigo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Descripcion)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Art_ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Codigo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descripcion)
            </td>
            <td>
                <button type="button" class="btn btn-secondary" data-toggle="ajax-modal" data-target="#addArticulo" data-url="@Url.Action("Edit/" + item.Art_ID.ToString())">Editar</button>
                <button type="button" class="btn btn-secondary" onclick="Delete(@item.Art_ID)">Eliminar</button>

            </td>
        </tr>
    }

</table>

<script type="text/javascript">
    $(function () {
        var PlaceHolderElement = $('#PlaceHolderHere');

        $('button[data-toggle="ajax-modal"]').click(function (event) {
            var url = $(this).data('url');
            var decodedUrl = decodeURIComponent(url);

            $.get(decodedUrl).done(function (data) {
                PlaceHolderElement.html(data);
                PlaceHolderElement.find('.modal').modal('show');
            })
        })

        PlaceHolderElement.on('click', '[data-save="modal"]', function (event) {
            var form = $(this).parents('.modal').find('form');
            var actionUrl = form.attr('action');
            var sendData = form.serialize();
            $.post(actionUrl, sendData).done(function (data) {
                PlaceHolderElement.find('.modal').modal('hide');
                location.reload(true)
            })
        })

    })


    function Delete(id) {
        debugger;
        var actionUrl = 'Delete/' + id;
        var sendData = id;
        $.post(actionUrl, sendData).done(function (data) {
            debugger;
            location.reload(true)
        })
    }



</script>

Evaluacion/Views/Articulos/_ArticuloData.cshtml
@model Evaluacion.Models.Articulo

<div class="modal face" id="addArticulo">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class=" modal-header">
                <h4 class="modal-title" id="addArticuloLabel"> Articulo</h4>
                <button type="button" class="close" data-mismiss="modal">
                    <span>x</span>
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Create", "Articulos", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @*<h4>Articulo</h4>
                            <hr />*@
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div id="Id_Articulo" class="form-group" disabled>
                            @Html.LabelFor(model => model.Art_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Art_ID, new { htmlAttributes = new { @class = "form-control", @disabled = "disabled" } })
                                @Html.ValidationMessageFor(model => model.Art_ID, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>

                    </div>
                }
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" data-save="modal">Guardar</button>
            </div>

        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Evaluacion/Views/Articulos/_ArticuloDataEdit.cshtml
@model Evaluacion.Models.Articulo

<div class="modal face" id="addArticulo">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class=" modal-header">
                <h4 class="modal-title" id="addArticuloLabel">Articulo</h4>
                <button type="button" class="close" data-mismiss="modal">
                    <span>x</span>
                </button>
            </div>
            <div class="modal-body">
                @using (Html.BeginForm("Edit", "Articulos", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-horizontal">
                        @*<h4>Articulo</h4>
                            <hr />*@
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <div class="form-group">
                            @Html.LabelFor(model => model.Art_ID, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Art_ID, new { htmlAttributes = new { @class = "form-control", @type = "hidden" } })
                                @Html.ValidationMessageFor(model => model.Art_ID, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            @Html.LabelFor(model => model.Descripcion, htmlAttributes: new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Descripcion, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.Descripcion, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                }
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" data-save="modal">Update</button>
            </div>

        </div>
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}